### ISSUE TITLE
Why unnecessary arguments?

### ISSUE THREAD

**Issue by musabgultekin** [mimoo/eureka#17]
``-encrypt``
Argument is not necessary as this project does only one thing.

``-file``
Is not necessary too. This project only encrypts files, not strings, its not necessary.

``-decrypt``
This can be detected using file suffix. Such as .enc or .encrypted. Not necessary too.

You're making this project much more complicated than it should be. Please, make it simple, like Go. :)

**Comment by musabgultekin** [comment]
Encrypting:
``eureka file.txt`` 
Decrypting
``eureka file.txt.enc``


How about that?

**Comment by mimoo** [comment]
I encourage you to submit a PR ;)

**Comment by musabgultekin** [comment]
After years, I returned back to this issue and I realized I used really rude language. I'm sorry for that @mimoo
