### ISSUE TITLE
Make it clear that the key must not be used twice

### ISSUE THREAD

**Issue by leonklingele** [mimoo/eureka#3]
Make it clear that the key must not be used twice to encrypt different files. Why not just use a random nonce and prepend it to the encrypted file?

**Comment by mimoo** [comment]
Thanks! As I remember you cannot pass a key when encrypting. So the key will be randomized at each encryption. If this is not correct feel free to re-open.

**Comment by leonklingele** [comment]
Arghh, misread the sources. Clever!

**Comment by leonklingele** [comment]
But then.. why not generate a random nonce alongside the random key? This will make it even more unlikely to repeat something which must not repeat.

**Comment by mimoo** [comment]
I could do that but:

* it would increase the size of the ciphertext
* the chance that you re-use a key after encrypting a file is 1/2^128 which is already considered more than enough
