### ISSUE TITLE
One-time key

### ISSUE THREAD

**Issue by Fastidious** [mimoo/eureka#4]
Is it, really, a one-time key? I can use it over and over to decrypt the same encrypted file. Perhaps it isn't one-time, but unique?

**Comment by mimoo** [comment]
I can see how the "one-time password" meaning would contradict with this one. But I don't think there is any formal definition for "one-time". The "one-time pad" for example is similar, it's a unique key but you can repeatedly use it to decrypt the same content. Hope that answers your question?
